require('dotenv').config();

module.exports = {
  PORT: process.env.PORT,
  API_URL: process.env.API_URL,
  CLIENT_URL: process.env.CLIENT_URL,

  PRIVATE_SECRET: process.env.PRIVATE_SECRET,
  JWT_TIME_TO_EXPIRE: process.env.JWT_TIME_TO_EXPIRE,

  MONGODB_URI: process.env.MONGODB_URI,

  SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
  SENDGRID_SENDER_EMAIL: process.env.SENDGRID_SENDER_EMAIL,

  VERIFY_EMAIL_TEMPLATE: process.env.VERIFY_EMAIL_TEMPLATE,
  PASSWORD_RECOVERY_TEMPLATE: process.env.PASSWORD_RECOVERY_TEMPLATE,
  CONTACT_REQUEST_TEMPLATE: process.env.CONTACT_REQUEST_TEMPLATE,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

  LINKEDIN_KEY: process.env.LINKEDIN_KEY,
  LINKEDIN_SECRET: process.env.LINKEDIN_SECRET,
}